### ISSUE TITLE
cargo build error

### ISSUE THREAD

**Issue by KnoooW** [MarginResearch/cannoli#1]
**cargo --version
cargo 1.61.0 (a028ae4 2022-04-29)

Linux CentOS7 X86-64**

==============================

   Compiling xcursor v0.3.4
   Compiling cexpr v0.6.0
   Compiling gpu-descriptor v0.2.2
   Compiling env_logger v0.9.0
   Compiling mempipe v0.1.0 (/data_sdd/qemu_highPerf/cannoli/mempipe)
error[E0432]: unresolved import `alloc::ffi`
  --> mempipe/src/lib.rs:55:12
   |
55 | use alloc::ffi::{CString, NulError};
   |            ^^^ could not find `ffi` in `alloc`

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> mempipe/src/lib.rs:29:1
   |
29 | #![feature(maybe_uninit_uninit_array, array_from_fn)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> mempipe/src/lib.rs:30:1
   |
30 | #![feature(inline_const, alloc_c_string)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> mempipe/src/lib.rs:29:12
   |
29 | #![feature(maybe_uninit_uninit_array, array_from_fn)]
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> mempipe/src/lib.rs:29:39
   |
29 | #![feature(maybe_uninit_uninit_array, array_from_fn)]
   |                                       ^^^^^^^^^^^^^

**Comment by KnoooW** [comment]
Solved by install rust nightly version.
Because alloc::ffi is nightly experiment api. (https://doc.rust-lang.org/nightly/alloc/ffi/index.html)

Steps:

rustup toolchain install nightly
cargo +nightly build --release

**Comment by gamozolabs** [comment]
That'll do it! Sorry yeah, have some nightly features I really don't like living without!
