### ISSUE TITLE
Cannoli sometimes misses instruction events (maybe only on self-modifying code)

### ISSUE THREAD

**Issue by trishume** [MarginResearch/cannoli#3]
Here's a reproducible test case of Cannoli missing an instruction execution event, with a readme: https://github.com/trishume/cannoli/tree/missing-trace-repro/examples/secrecy

**Comment by gamozolabs** [comment]
Fixed. The QEMU JIT can call C functions directly that then can `longjmp()` _out_ of the JIT. Really fun... Added strict checking to make sure JIT entries always are followed by exits, and also added some checking to make sure JIT exits from the C side of QEMU are correct by using a poison value.

If we "missed" another place where QEMU can exit the JIT, we should now panic by detecting either A. back-to-back JIT entry calls (panic), or B. a JIT exit call with a poison value (meaning that QEMU tried to `longjmp()` but from a context we don't know).

I've tried to design it such that the value is _not_ poisoned for as short of a time as possible, to ensure that if we ever `longjmp()` out of the JIT from an unknown context, we are very likely to catch it in a very clean manner.
